import type { StrategyDocument } from "@limit-canvas/hook-dsl";

export interface GeneratedArtifact {
  relativePath: string;
  content: string;
}

export function generateStopLossStrategy(doc: StrategyDocument): string {
  const b = doc.block;
  if (b.type !== "stop-loss") throw new Error("expected stop-loss block");
  return `// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

interface IPriceOracle {
    function latestAnswer() external view returns (int256);
}

/// @title StopLossStrategy — generated by Limit Canvas
/// @notice View helper for stop-loss / take-profit predicates via LOP arbitraryStaticCall
contract StopLossStrategy {
    /// @notice Returns 1 if price condition passes, 0 otherwise (LOP predicate convention)
    function checkPrice(address oracle, uint256 threshold, bool directionAbove) external view returns (uint256) {
        int256 answer = IPriceOracle(oracle).latestAnswer();
        require(answer > 0, "invalid oracle answer");
        uint256 price = uint256(answer);
        bool ok = directionAbove ? price > threshold : price < threshold;
        return ok ? 1 : 0;
    }
}
`;
}

export function generateGasGuardStrategy(doc: StrategyDocument): string {
  const b = doc.block;
  if (b.type !== "gas-guard") throw new Error("expected gas-guard block");
  return `// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

/// @title GasGuardStrategy — generated by Limit Canvas
/// @notice Fill only when block.basefee <= maxBaseFee (${b.maxGwei} gwei cap in DSL)
contract GasGuardStrategy {
    function isAllowed(uint256 maxBaseFee) external view returns (bool) {
        return block.basefee <= maxBaseFee;
    }

    /// @notice LOP predicates expect uint256 (non-zero = pass)
    function isAllowedUint(uint256 maxBaseFee) external view returns (uint256) {
        return isAllowed(maxBaseFee) ? 1 : 0;
    }
}
`;
}

export function generateTwapSliceGetter(doc: StrategyDocument): string {
  const b = doc.block;
  if (b.type !== "twap-slice") throw new Error("expected twap-slice block");
  return `// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

/// @title TwapSliceGetter — generated by Limit Canvas
/// @notice Caps per-fill making amount for TWAP-style partial fills
contract TwapSliceGetter {
    uint256 public immutable totalAmount;
    uint256 public immutable sliceAmount;
    uint256 public immutable intervalSeconds;
    uint256 public immutable startTime;

    constructor(uint256 _total, uint256 _slice, uint256 _interval, uint256 _start) {
        totalAmount = _total;
        sliceAmount = _slice;
        intervalSeconds = _interval;
        startTime = _start;
    }

    function maxMakingAmountNow() public view returns (uint256) {
        if (block.timestamp < startTime) return 0;
        uint256 elapsed = block.timestamp - startTime;
        uint256 slices = elapsed / intervalSeconds + 1;
        uint256 allowed = slices * sliceAmount;
        if (allowed > totalAmount) allowed = totalAmount;
        return allowed;
    }

    function getMakingAmount(
        uint256 requestedMaking,
        uint256 remainingMaking,
        bytes32 /* orderHash */
    ) external view returns (uint256) {
        uint256 cap = maxMakingAmountNow();
        uint256 maxFill = cap > remainingMaking ? remainingMaking : cap;
        return requestedMaking > maxFill ? maxFill : requestedMaking;
    }
}
`;
}

export function generateDcaRegistry(doc: StrategyDocument): string {
  const b = doc.block;
  if (b.type !== "dca-schedule") throw new Error("expected dca-schedule block");
  return `// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

/// @title DcaSeriesRegistry — generated by Limit Canvas
/// @notice On-chain metadata for DCA tranche series (orders signed off-chain)
contract DcaSeriesRegistry {
    event DcaSeriesRegistered(
        bytes32 indexed seriesKey,
        address indexed maker,
        uint256 tranches,
        uint256 amountPerTranche,
        uint256 intervalSeconds
    );

    struct Series {
        address maker;
        uint256 tranches;
        uint256 amountPerTranche;
        uint256 intervalSeconds;
    }

    mapping(bytes32 => Series) public series;

    function registerSeries(
        address maker,
        uint256 tranches,
        uint256 amountPerTranche,
        uint256 intervalSeconds,
        uint256 seriesId
    ) external returns (bytes32 key) {
        key = keccak256(abi.encode(maker, seriesId, block.chainid));
        series[key] = Series(maker, tranches, amountPerTranche, intervalSeconds);
        emit DcaSeriesRegistered(key, maker, tranches, amountPerTranche, intervalSeconds);
    }
}
`;
}

export function generateDeployScript(
  contractName: string,
  templateId: string,
): string {
  return `// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

import {Script} from "forge-std/Script.sol";
import {console2} from "forge-std/console2.sol";

contract Deploy${contractName} is Script {
    function run() external {
        uint256 key = vm.envUint("DEPLOYER_KEY");
        vm.startBroadcast(key);
        // Deploy implementation — replace with actual constructor args from DSL
        console2.log("Deploy ${templateId} — set DEPLOYER_KEY and RPC_URL");
        vm.stopBroadcast();
    }
}
`;
}

export function generateTestStub(contractName: string): string {
  return `// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

import {Test} from "forge-std/Test.sol";

contract ${contractName}GeneratedTest is Test {
    function test_placeholder() external pure {
        assert(true);
    }
}
`;
}

export function generateReadme(
  doc: StrategyDocument,
  extensionHash: string,
): string {
  return `# Generated: ${doc.name}

Template: **${doc.templateId}**
Chain: ${doc.network.chainId}
LOP: \`${doc.network.lopAddress}\`

## Extension hash (salt low 160 bits)

\`${extensionHash}\`

## Fill checklist

1. Set makerTraits **HAS_EXTENSION** (bit 249)
2. Pass extension calldata from \`extensions.json\` when filling
3. Run \`forge test\` in packages/contracts

## Keeper (DCA/TWAP)

${doc.templateId === "dca-schedule" ? "Schedule off-chain fills per tranche interval. See DcaSeriesRegistry events." : doc.templateId === "twap-slice" ? "Allow partial fills; respect slice getter cap." : "N/A"}

## Risk notes

${riskNotes(doc)
  .map((risk) => `- ${risk}`)
  .join("\n")}

## Reproduce

\`\`\`bash
bun run codegen examples/${doc.templateId}.json ./artifacts/${doc.templateId}
cd packages/contracts && forge test -vvv
cd packages/contracts && forge snapshot --match-path "test/benchmark/*"
\`\`\`

## Mainnet blockers

- Confirm template catalog maturity is \`audit-ready\` or \`mainnet-enabled\`
- Set \`audited: true\` in your strategy DSL and run with \`FOUNDRY_PROFILE=mainnet\`
- Review \`manifest.json\` and the extension hash (note: \`bytecodeHash\` is reserved but not yet populated)
- Confirm chain ID and LOP address match the official 1inch deployment
- Resolve all warnings before broadcast
`;
}

function riskNotes(doc: StrategyDocument): string[] {
  switch (doc.templateId) {
    case "stop-loss":
      return [
        "Oracle price freshness and decimals must match the configured threshold.",
        "A stale or compromised oracle can make the order fill unexpectedly.",
      ];
    case "gas-guard":
      return [
        "Base fee behavior differs across some L2s.",
        "Strict gas caps may prevent otherwise profitable fills.",
      ];
    case "twap-slice":
      return [
        "TWAP fills depend on taker or keeper liveness.",
        "Partial fill accounting must be reviewed before mainnet use.",
      ];
    case "dca-schedule":
      return [
        "DCA execution depends on off-chain order publication and keeper behavior.",
        "Series metadata is informational and does not execute tranches itself.",
      ];
    default:
      return ["Review generated code and assumptions before use."];
  }
}
